apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: synapse
type: Opaque
stringData:
  DATABASE_URL: ""postgresql://doadmin:AVNS_YjWXReTbi5Epp6MzXjq@sh-shared-postgres-do-user-29516566-0.f.db.ondigitalocean.com:25060/__APP_SLUG__?sslmode=require""
  DO_SPACES_KEY: ""
  DO_SPACES_SECRET: ""
  DIGITALOCEAN_MODEL_KEY: ""

