name: synapse
region: nyc
domains:
  - domain: synapse.shtrial.com
    type: ALIAS
    zone: shtrial.com

static_sites:
  - name: frontend
    image:
      registry_type: DOCKER_HUB
      repository: shmindmaster/synapse-frontend
      tag: latest

services:
  - name: backend
    image:
      registry_type: DOCKER_HUB
      repository: shmindmaster/synapse-backend
      tag: latest
    http_port: 8000
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${DATABASE_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        value: ${OPENAI_API_KEY}
      - key: AUTH_SECRET
        scope: RUN_TIME
        value: ${AUTH_SECRET}

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: backend
    - match:
        path:
          prefix: /
      component:
        name: frontend
