name: synapse
region: nyc
features:
- buildpack-stack=ubuntu-22
domains:
- domain: synapse.shtrial.com
  type: PRIMARY
  zone: shtrial.com
- domain: api-synapse.shtrial.com
  type: ALIAS
  zone: shtrial.com
ingress:
  rules:
  - match:
      authority:
        exact: api-synapse.shtrial.com
      path:
        prefix: /
    component:
      name: backend
      preserve_path_prefix: true
    cors:
      allow_origins:
      - exact: https://synapse.shtrial.com
      - exact: https://synapse.ondigitalocean.app
      allow_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
      allow_headers:
      - '*'
      allow_credentials: true
  - match:
      authority:
        exact: synapse.shtrial.com
      path:
        prefix: /
    component:
      name: frontend
  - match:
      authority:
        exact: synapse.ondigitalocean.app
      path:
        prefix: /
    component:
      name: frontend
services:
- name: frontend
  source_dir: apps/frontend
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: shmindmaster/synapse
  http_port: 3000
  instance_size_slug: basic-xs
  health_check:
    http_path: /
    initial_delay_seconds: 30
    period_seconds: 10
envs:
  - key: NODE_ENV
    value: production
  - key: VITE_API_URL
    value: https://api-synapse.shtrial.com
    scope: RUN_AND_BUILD_TIME
  - key: VITE_APP_URL
    value: https://synapse.shtrial.com
    scope: RUN_AND_BUILD_TIME
  - key: NEXT_PUBLIC_SENTRY_DSN
    value: https://8d213bde5ea54d48fbf78ab27ef49a0e@o4509123874127872.ingest.us.sentry.io/4510495664177153
    scope: RUN_AND_BUILD_TIME
- name: backend
  source_dir: apps/backend
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: shmindmaster/synapse
  http_port: 8000
  instance_size_slug: basic-xs
  health_check:
    http_path: /health
    initial_delay_seconds: 20
    period_seconds: 10
  envs:
  - key: APP_SLUG
    value: synapse
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: postgresql://doadmin:AVNS_YjWXReTbi5Epp6MzXjq@sh-shared-postgres-do-user-29516566-0.f.db.ondigitalocean.com:25060/synapse?sslmode=require
    type: SECRET
  - key: DATABASE_URL_UNPOOLED
    value: postgresql://doadmin:AVNS_YjWXReTbi5Epp6MzXjq@sh-shared-postgres-do-user-29516566-0.f.db.ondigitalocean.com:25060/synapse?sslmode=require
    type: SECRET
  - key: PGSSLMODE
    value: require
  - key: AUTH_SECRET
    value: super-secret-auth-key-change-in-prod
    type: SECRET
  - key: DO_INFERENCE_API_KEY
    value: sk-do-wRHPdHRsQkNhkcY8UwE4t4sFeCOkVnMPubdbUqSoZYTHTH_J-cEdDslcN9
    type: SECRET
  - key: OPENAI_DIRECT_API_KEY
    value: sk-do-wRHPdHRsQkNhkcY8UwE4t4sFeCOkVnMPubdbUqSoZYTHTH_J-cEdDslcN9
    type: SECRET
  - key: SPACES_KEY
    value: DO00LMB24WZXVCMK6G22
    type: SECRET
  - key: SPACES_SECRET
    value: iF+p6XAKezSNNCKsIB3f0XGS+6/gmDE+8VPZCyyBU1o
    type: SECRET
  - key: SPACES_ENDPOINT
    value: https://nyc3.digitaloceanspaces.com
  - key: SPACES_BUCKET
    value: sh-storage
  - key: SPACES_REGION
    value: nyc3
  - key: OBJECT_STORAGE_PREFIX
    value: synapse/
  - key: MODEL_CHAT
    value: openai-gpt-oss-120b
  - key: MODEL_FAST
    value: openai-gpt-oss-20b
  - key: MODEL_EMBEDDING
    value: ai/embeddinggemma
  - key: MODEL_IMAGE
    value: fal-ai/fast-sdxl
  - key: MODEL_TTS
    value: fal-ai/elevenlabs/tts/multilingual-v2
  - key: SENTRY_DSN
    value: https://e6a72d285ed5daa34316027af942fb97@o4509123874127872.ingest.us.sentry.io/4510495664111616
    type: SECRET
jobs:
- name: migrate-db
  kind: POST_DEPLOY
  source_dir: apps/backend
  dockerfile_path: Dockerfile
  run_command: ./scripts/migrate.sh
  instance_size_slug: basic-xs
  github:
    branch: main
    repo: shmindmaster/synapse
  envs:
  - key: DATABASE_URL
    value: postgresql://doadmin:AVNS_YjWXReTbi5Epp6MzXjq@sh-shared-postgres-do-user-29516566-0.f.db.ondigitalocean.com:25060/synapse?sslmode=require
    type: SECRET
  - key: APP_SLUG
    value: synapse