name: synapse
services:
- name: web
  source_dir: /
  github:
    repo: shmindmaster/Synapse
    branch: main
  run_command: sh -c "npx prisma migrate deploy && node apps/backend/server.js"
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: DIGITALOCEAN_INFERENCE_ENDPOINT
    value: "https://inference.do-ai.run/v1"
  - key: AI_MODEL
    value: "llama-3.1-70b-instruct"
  - key: AI_MODEL_EMBEDDING
    value: "text-embedding-3-small"
  - key: DO_SPACES_ENDPOINT
    value: "https://nyc3.digitaloceanspaces.com"
  - key: DO_SPACES_BUCKET
    value: "synapse"
  - key: DO_SPACES_REGION
    value: "nyc3"
  - key: DO_SPACES_CDN_ENDPOINT
    value: "https://synapse.nyc3.cdn.digitaloceanspaces.com"
  - key: NEXT_PUBLIC_CDN_BASE_URL
    value: "https://synapse.nyc3.cdn.digitaloceanspaces.com"
  http_port: 3000
  routes:
  - path: /
databases:
- name: db
  engine: PG
  version: "15"
  # Connect to existing shared cluster
  production: true
