apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-backend
  namespace: synapse
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shtrial-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse
        app.kubernetes.io/instance: synapse
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: shtrial-platform
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
      - name: synapse-backend
        image: registry.digitalocean.com/shtrial-reg/synapse-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - secretRef:
            name: app-secrets
        env:
        - name: PORT
          value: "8000"
        - name: APP_SLUG
          value: "synapse"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-backend
  namespace: synapse
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shtrial-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: backend
  ports:
  - port: 4000
    targetPort: 8000
    protocol: TCP
    name: http
