apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-frontend
  namespace: synapse
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: shtrial-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse
        app.kubernetes.io/instance: synapse
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: shtrial-platform
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
      - name: synapse-frontend
        image: registry.digitalocean.com/shtrial-reg/synapse-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: 'production'
        - name: NEXT_PUBLIC_API_URL
          value: 'https://api-synapse.shtrial.com'
        - name: NEXT_PUBLIC_CDN_BASE_URL
          value: 'https://sh-storage.nyc3.cdn.digitaloceanspaces.com/synapse'
        envFrom:
        - secretRef:
            name: app-secrets
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-frontend
  namespace: synapse
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: shtrial-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/component: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
